version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 99
    allow:
      - dependency-type: all
    groups:
      aws-deps:
        patterns:
          - aws*
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - *
