source 'https://rubygems.org'
ruby '~> 3.4'

# Middleman
gem 'middleman'
gem 'sassc', github: 'sass/sassc-ruby', ref: 'refs/pull/233/head'
gem 'sassc-embedded'
gem 'middleman-gh-pages'
gem 'middleman-syntax'
gem 'middleman-autoprefixer'
gem 'middleman-sprockets'
gem 'rouge'
gem 'redcarpet'

gem 'middleman-livereload'
gem 'rake'
gem 'aws-sdk-s3'
gem 'parallel'
gem 'listen'
gem 'mime-types'
gem 'html-proofer'